
export const FETCH_COIN_DETAILS_REQUEST = "FETCH_COIN_DETAILS_REQUEST";
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";
export const FETCH_COIN_DETAILS_FAILURE = "FETCH_COIN_DETAILS_FAILURE";